from __future__ import annotations

from dataclasses import dataclass


TRANSLATIONS: dict[str, dict[str, str]] = {
    "pt-BR": {
        "app.title": "PyCQLog",
        "menu.app": "Aplicacao",
        "menu.language": "Idioma",
        "menu.settings": "Configuracoes",
        "menu.directories": "Diretorios",
        "menu.theme": "Tema",
        "menu.dashboard": "Dashboard",
        "menu.dashboard_open": "Abrir Dashboard",
        "menu.logbooks": "Logbooks",
        "menu.station_profiles": "Perfis",
        "menu.integrations": "Integracoes",
        "menu.integration_settings": "Remotos",
        "menu.integration_monitor": "Monitor da Integracao",
        "menu.adif": "ADIF",
        "menu.adif_preferences": "Preferencias ADIF",
        "menu.import_adif": "Importar ADIF",
        "menu.export_adif": "Exportar ADIF",
        "menu.export_lotw": "Exportar & Assinar ADIF (LoTW)",
        "menu.help": "Ajuda",
        "menu.exit": "Sair",
        "menu.about": "Sobre",
        "language.pt-BR": "Portugues (Brasil)",
        "language.en": "English",
        "section.manual_entry": "Registro Manual de QSO",
        "section.operation_console": "Console Operacional",
        "section.operation_console_hint": "Fluxo inspirado em estações de operação, com captura rápida, log central e contexto sempre visível.",
        "section.qso_capture": "Captura do QSO",
        "section.qso_capture_hint": "Priorize callsign, frequência e modo. O restante do contexto fica ao lado para reduzir troca de foco.",
        "section.recent_qsos": "QSOs Recentes",
        "section.callsign_history": "Historico do Callsign",
        "section.station_context": "Contexto da Estação",
        "section.station_context_hint": "Acompanhe logbook ativo, integrações e histórico do callsign atual sem sair da tela principal.",
        "section.quick_filters": "Filtros rapidos",
        "label.callsign": "Callsign",
        "label.date": "Data",
        "label.time": "Hora",
        "label.frequency_mhz": "Frequencia MHz",
        "label.mode": "Modo",
        "label.rst_sent": "RST Enviado",
        "label.rst_recv": "RST Recebido",
        "label.operator": "Operador",
        "label.station": "Estacao",
        "label.notes": "Notas",
        "placeholder.callsign": "PY2XXX",
        "placeholder.date": "AAAA-MM-DD",
        "placeholder.time": "HH:MM",
        "placeholder.frequency": "14.074",
        "placeholder.mode": "SSB, CW, FT8",
        "placeholder.rst": "59",
        "placeholder.operator": "Callsign do operador",
        "placeholder.station": "Callsign da estacao",
        "placeholder.notes": "Notas sobre o contato",
        "placeholder.search_callsign": "Buscar callsign",
        "button.save_qso": "Salvar QSO",
        "button.update_qso": "Atualizar QSO",
        "button.new_qso": "Novo QSO",
        "button.search": "Buscar",
        "button.show_recent": "Mostrar Recentes",
        "button.edit_selected": "Editar Selecionado",
        "button.delete_selected": "Excluir Selecionado",
        "button.manage_logbooks": "Gerenciar",
        "button.new_profile": "Novo perfil",
        "button.save_profile": "Salvar perfil",
        "button.delete_profile": "Excluir perfil",
        "button.new_logbook": "Novo logbook",
        "button.save_logbook": "Salvar logbook",
        "button.delete_logbook": "Excluir logbook",
        "button.close": "Fechar",
        "table.recent.id": "ID",
        "table.recent.callsign": "Callsign",
        "table.recent.date": "Data",
        "table.recent.time": "Hora",
        "table.recent.band": "Banda",
        "table.recent.mode": "Modo",
        "table.history.id": "ID",
        "table.history.date": "Data",
        "table.history.time": "Hora",
        "table.history.band": "Banda",
        "table.history.mode": "Modo",
        "table.history.rst": "RST",
        "status.ready_first": "Pronto para registrar o primeiro QSO.",
        "status.ready_next": "Pronto para registrar o proximo QSO.",
        "status.search_loaded": "{count} QSO(s) carregado(s) para a busca.",
        "status.editing": "Editando QSO #{qso_id} de {callsign}.",
        "status.deleted": "QSO #{qso_id} excluido.",
        "status.logbook_changed": "Logbook ativo alterado para {name}.",
        "status.saved": "QSO #{qso_id} {action} para {callsign} em {band} {mode}.{warnings}",
        "status.adif_imported": "Importacao ADIF concluida. {imported} importado(s), {skipped} ignorado(s), {failed} falha(s).",
        "status.adif_exported": "Exportacao ADIF concluida. {exported} QSO(s) exportado(s).",
        "status.history_prompt": "Digite ou selecione um callsign para inspecionar QSOs anteriores.",
        "status.history_found": "{count} QSO(s) anterior(es) encontrado(s) para {callsign}.",
        "status.history_empty": "Nenhum QSO anterior encontrado para {callsign}.",
        "status.integration_logged": "{source} registrou {callsign} em {band} {mode}.",
        "status.integration_parse_failed": "Falha ao interpretar ADIF recebido de {source}.",
        "status.integration_save_failed": "Falha ao salvar QSO recebido de {source}: {detail}",
        "status.clublog_queued": "Upload para Club Log enfileirado. {detail}",
        "status.clublog_upload_ok": "Club Log atualizado com sucesso. {detail}",
        "status.clublog_upload_failed": "Falha no envio ao Club Log. {detail}",
        "message.invalid_data_title": "Dados invalidos",
        "message.invalid_frequency": "A frequencia deve ser um numero decimal valido.",
        "message.validation_error_title": "Erro de validacao",
        "message.qso_saved_title": "QSO salvo",
        "message.qso_saved_body": "QSO #{qso_id} {action} para {callsign} em {band}.",
        "message.qso_not_found_title": "QSO nao encontrado",
        "message.qso_not_found_body": "QSO #{qso_id} nao foi encontrado.",
        "message.delete_title": "Excluir QSO",
        "message.delete_body": "Deseja excluir o QSO #{qso_id}?",
        "message.delete_failed_title": "Falha ao excluir",
        "message.delete_failed_body": "O QSO #{qso_id} nao pode ser excluido.",
        "action.saved": "salvo",
        "action.updated": "atualizado",
        "about.title": "Sobre o PyCQLog",
        "about.body": (
            "<h2>PyCQLog</h2>"
            "<p>Aplicacao desktop para radioamadorismo desenvolvida em Python e PyQt.</p>"
            "<p><b>Autor:</b> Claudio - PY9MT<br>"
            "<b>Co-criacao tecnica:</b> CODEX</p>"
            "<p>Este sistema esta sendo construido com apoio de IA altamente qualificada, "
            "com foco em valor estrategico, velocidade de evolucao e qualidade arquitetural.</p>"
        ),
        "settings.title": "Configuracoes",
        "settings.language": "Idioma",
        "settings.theme": "Tema",
        "settings.operator_callsign": "Callsign padrao do operador",
        "settings.station_callsign": "Callsign padrao da estacao",
        "settings.data_dir": "Diretorio de dados",
        "settings.data_dir_help": "Define onde o PyCQLog grava banco local e configuracoes.",
        "settings.log_dir": "Diretorio padrao dos logs",
        "settings.log_dir_help": "Define a pasta padrao para arquivos ADIF e outros logs.",
        "settings.choose_directory": "Selecionar pasta",
        "settings.restart_notice": "Algumas mudancas podem exigir reinicio para refletir em toda a aplicacao.",
        "settings.saved_title": "Configuracoes salvas",
        "settings.saved_body": "As configuracoes foram salvas com sucesso.",
        "settings.invalid_data_dir_title": "Diretorio invalido",
        "settings.invalid_data_dir_body": "Nao foi possivel criar ou acessar o diretorio informado.",
        "settings.directory_dialog_title": "Selecionar diretorio de dados",
        "settings.invalid_log_dir_title": "Diretorio de logs invalido",
        "settings.invalid_log_dir_body": "Nao foi possivel criar ou acessar o diretorio padrao dos logs.",
        "settings.log_dir_dialog_title": "Selecionar diretorio padrao dos logs",
        "directories.title": "Diretorios",
        "directories.help": "Define os caminhos usados pelo sistema para banco local e arquivos de log.",
        "logbooks.title": "Logbooks",
        "logbooks.active": "Logbook ativo",
        "logbooks.name": "Nome",
        "logbooks.description": "Descricao",
        "logbooks.operator_profile": "Perfil de operador",
        "logbooks.station_profile": "Perfil de estacao",
        "logbooks.no_profile": "Sem perfil",
        "logbooks.qso_count": "QSOs",
        "logbooks.help": "Cada logbook pode representar uma operacao distinta, como principal, contest, portable ou expedicao.",
        "logbooks.name_required": "Informe um nome para o logbook.",
        "logbooks.delete_title": "Excluir logbook",
        "logbooks.delete_body": "Deseja excluir o logbook selecionado? Os QSOs deste logbook tambem serao removidos.",
        "logbooks.delete_blocked_title": "Exclusao bloqueada",
        "logbooks.delete_blocked_body": "Nao e possivel excluir o ultimo logbook restante.",
        "profiles.title": "Perfis de estacao e operador",
        "profiles.name": "Nome do perfil",
        "profiles.type": "Tipo",
        "profiles.type_both": "Operador e estacao",
        "profiles.type_operator": "Somente operador",
        "profiles.type_station": "Somente estacao",
        "profiles.qth": "QTH",
        "profiles.locator": "Locator",
        "profiles.power": "Potencia",
        "profiles.antenna": "Antena",
        "profiles.help": "Perfis reutilizaveis ajudam a montar logbooks e operacoes com dados consistentes.",
        "profiles.name_required": "Informe um nome para o perfil.",
        "profiles.delete_title": "Excluir perfil",
        "profiles.delete_body": "Deseja excluir o perfil selecionado?",
        "integrations.title": "Integracoes",
        "integrations.wsjt_enabled": "Ativar captura automatica via WSJT-X / JTDX UDP",
        "integrations.wsjt_debug": "Habilitar Debug UDP (Ver todos pacotes no Monitor)",
        "integrations.wsjt_host": "Host local UDP",
        "integrations.wsjt_port": "Porta UDP",
        "integrations.clublog_enabled": "Ativar envio automatico ao Club Log",
        "integrations.clublog_upload_udp": "Enviar automaticamente QSOs recebidos via WSJT-X / JTDX",
        "integrations.clublog_upload_manual": "Enviar automaticamente QSOs salvos manualmente",
        "integrations.clublog_email": "Email do Club Log",
        "integrations.clublog_password": "App password do Club Log",
        "integrations.clublog_callsign": "Callsign principal",
        "integrations.clublog_api_key": "API key",
        "integrations.clublog_endpoint": "Endpoint de envio",
        "integrations.clublog_delete_endpoint": "Endpoint de exclusao",
        "integrations.clublog_interval": "Intervalo minimo entre envios (s)",
        "integrations.qrz_enabled": "Ativar envio automatico ao QRZ",
        "integrations.qrz_upload_udp": "Enviar rapidamente QSOs recebidos via WSJT-X",
        "integrations.qrz_upload_manual": "Enviar rapidamente QSOs salvos manualmente",
        "integrations.qrz_username": "QRZ Username (Para lookup XML)",
        "integrations.qrz_password": "QRZ Password",
        "integrations.qrz_api_key": "QRZ Logbook API Key (Para upload)",
        "integrations.lotw_tqsl_path": "Comando/Caminho do tqsl",
        "integrations.lotw_station_location": "Station Location (TQSL)",
        "integrations.tab_local": "WSJT-X",
        "integrations.tab_clublog": "Club Log",
        "integrations.tab_qrz": "QRZ.com",
        "integrations.tab_lotw": "LoTW",
        "integrations.tab_service": "Servico",
        "integrations.service_remote_enabled": "Usar daemon remoto nesta interface",
        "integrations.service_remote_host": "IP/host do daemon",
        "integrations.service_remote_port": "Porta do daemon",
        "integrations.service_auth_code": "Codigo de autenticacao",
        "integrations.service_auth_generate": "Gerar codigo",
        "integrations.service_help": "Essas opcoes controlam apenas a conexao da interface grafica com um daemon remoto. As configuracoes do daemon ficam no arquivo pycqlog_daemon.conf.",
        "integrations.help": "Configure os parametros de integracao pelas abas. Lookups do QRZ necessitam de usuario/senha de assinatura ativa XML. Envios para Logbook do QRZ necessitam da Logbook API Key. O utilitario tqsl deve estar instalado para LoTW.",
        "integrations.monitor_title": "Monitor da Integracao",
        "integrations.monitor_listener": "Listener UDP",
        "integrations.monitor_clublog": "Club Log",
        "integrations.monitor_received": "Pacotes recebidos",
        "integrations.monitor_saved": "QSOs salvos",
        "integrations.monitor_uploaded": "Envios concluídos",
        "integrations.monitor_failed": "Falhas",
        "integrations.monitor_pending": "Pendentes",
        "integrations.monitor_time": "Hora",
        "integrations.monitor_source": "Origem",
        "integrations.monitor_event": "Evento",
        "integrations.monitor_detail": "Detalhe",
        "integrations.monitor_on": "Ativo",
        "integrations.monitor_off": "Inativo",
        "integrations.monitor_test_udp": "Teste UDP",
        "integrations.monitor_test_clublog": "Teste Club Log",
        "integrations.monitor_retry_pending": "Reenfileirar pendentes",
        "integrations.monitor_clear": "Limpar historico",
        "integrations.event_received": "Pacote recebido",
        "integrations.event_saved": "QSO salvo",
        "integrations.event_uploaded": "Upload concluido",
        "integrations.event_upload_failed": "Upload falhou",
        "integrations.event_queued": "Upload enfileirado",
        "integrations.event_parse_failed": "Falha no parse",
        "integrations.event_save_failed": "Falha ao salvar",
        "integrations.event_test_udp": "Teste UDP disparado",
        "integrations.event_test_clublog": "Teste Club Log enfileirado",
        "integrations.event_test_clublog_failed": "Teste Club Log bloqueado",
        "integrations.event_retry_pending": "Pendentes reenfileirados",
        "integrations.test_udp_detail": "Um pacote ADIF sintético foi inserido na fila local.",
        "button.save_settings": "Salvar configuracoes",
        "button.cancel": "Cancelar",
        "adif.dialog_title": "Selecionar arquivo ADIF",
        "adif.settings_title": "Preferencias ADIF",
        "adif.settings_help": "Define os valores padrao usados no formulario e no nome sugerido da exportacao ADIF.",
        "adif.export_prefix": "Prefixo do arquivo de exportacao",
        "adif.export_prefix_placeholder": "pycqlog_export",
        "adif.import_title": "Importacao ADIF",
        "adif.import_result": "{imported} QSO(s) importado(s), {skipped} ignorado(s), {failed} falha(s).",
        "adif.export_dialog_title": "Salvar exportacao ADIF",
        "adif.export_filters_title": "Filtros da exportacao ADIF",
        "adif.export_filters_help": "Todos os filtros sao opcionais. Datas devem usar o formato AAAA-MM-DD.",
        "adif.export_choose_file": "Escolher arquivo",
        "adif.export_date_from": "Data inicial",
        "adif.export_date_to": "Data final",
        "adif.export_band": "Banda",
        "adif.export_title": "Exportacao ADIF",
        "adif.export_result": "{exported} QSO(s) exportado(s) para:\n{destination}",
        "adif.preview_title": "Pre-visualizacao da importacao ADIF",
        "adif.preview_summary": "Total: {total} | Prontos: {ready} | Ignorados: {skipped} | Falhas: {failed}",
        "adif.preview_import": "Importar",
        "adif.preview_status": "Status",
        "adif.preview_confirm": "Importar agora",
        "adif.filter_label": "Filtro",
        "adif.filter_all": "Todos",
        "adif.filter_ready": "Prontos",
        "adif.filter_skipped": "Ignorados",
        "adif.filter_failed": "Falhas",
        "adif.select_ready": "Marcar prontos",
        "adif.clear_selection": "Limpar selecao",
        "filter.band": "Bandas",
        "filter.mode": "Modos",
        "filter.clear": "Limpar filtros",
        "theme.system": "Usar tema do sistema",
        "theme.light": "Claro",
        "theme.dark": "Escuro",
        "dashboard.title": "Dashboard Operacional",
        "dashboard.active_logbook": "Logbook ativo: {name}",
        "dashboard.period": "Periodo",
        "dashboard.period_all": "Todo o log",
        "dashboard.period_7d": "Ultimos 7 dias",
        "dashboard.period_30d": "Ultimos 30 dias",
        "dashboard.period_365d": "Ultimos 12 meses",
        "dashboard.settings_menu": "Cores e aparencia",
        "dashboard.settings_title": "Cores do Dashboard",
        "dashboard.settings_band_colors": "Usar cores por banda nos graficos de banda",
        "dashboard.settings_mode_colors": "Usar cores por modo nos graficos de modo",
        "dashboard.settings_table_colors": "Colorir tambem banda e modo nas tabelas principais",
        "dashboard.settings_help": "Quando ativo, os graficos do dashboard usam paletas especificas por banda e por modo de operacao. Essas cores tambem podem ser aplicadas nas tabelas de operacao.",
        "dashboard.total_qsos": "Total de QSOs",
        "dashboard.unique_callsigns": "Callsigns unicos",
        "dashboard.active_bands": "Bandas ativas",
        "dashboard.active_modes": "Modos ativos",
        "dashboard.dxcc_entities": "DXCC estimado",
        "dashboard.waz_zones": "CQ zones",
        "dashboard.wpx_prefixes": "WPX prefixes",
        "dashboard.chart_bands": "QSOs por banda",
        "dashboard.chart_modes": "QSOs por modo",
        "dashboard.chart_days": "QSOs por dia",
        "dashboard.chart_months": "Evolucao mensal",
        "dashboard.chart_hours": "QSOs por hora",
        "dashboard.top_callsigns": "Top callsigns",
        "dashboard.contacts": "Contatos",
        "summary.logbook": "Logbook",
        "summary.integrations": "Integrações",
        "summary.pending": "Pendentes",
        "summary.status": "Status operacional",
        "summary.visible_qsos": "{count} QSO(s) visíveis nesta lista.",
        "summary.logbook_detail": "{name} com {count} QSO(s) no log ativo.",
        "summary.logbook_footer": "Logbook: {name} ({count} QSOs)",
        "summary.integration_listener_on": "UDP ativo",
        "summary.integration_listener_off": "UDP inativo",
        "summary.integration_cloud_on": "Upload pronto",
        "summary.integration_cloud_off": "Upload limitado",
        "summary.integrations_detail": "Listener: {listener}\nClub Log: {cloud}\nFila pendente: {pending}",
        "summary.integrations_footer": "Integrações: UDP {listener} | Club Log {cloud}",
        "summary.pending_footer": "Fila: {pending}",
    },
    "en": {
        "app.title": "PyCQLog",
        "menu.app": "Application",
        "menu.language": "Language",
        "menu.settings": "Settings",
        "menu.directories": "Directories",
        "menu.theme": "Theme",
        "menu.dashboard": "Dashboard",
        "menu.dashboard_open": "Open Dashboard",
        "menu.logbooks": "Logbooks",
        "menu.station_profiles": "Profiles",
        "menu.integrations": "Integrations",
        "menu.integration_settings": "Remotes",
        "menu.integration_monitor": "Integration Monitor",
        "menu.adif": "ADIF",
        "menu.adif_preferences": "ADIF Preferences",
        "menu.import_adif": "Import ADIF",
        "menu.export_adif": "Export ADIF",
        "menu.export_lotw": "Export & Sign ADIF (LoTW)",
        "menu.help": "Help",
        "menu.exit": "Exit",
        "menu.about": "About",
        "language.pt-BR": "Portuguese (Brazil)",
        "language.en": "English",
        "section.manual_entry": "Manual QSO Entry",
        "section.operation_console": "Operations Console",
        "section.operation_console_hint": "Inspired by radio operating consoles, with fast capture, a central log view, and always-on context.",
        "section.qso_capture": "QSO Capture",
        "section.qso_capture_hint": "Keep callsign, frequency, and mode up front. The rest of the context stays visible beside the form.",
        "section.recent_qsos": "Recent QSOs",
        "section.callsign_history": "Callsign History",
        "section.station_context": "Station Context",
        "section.station_context_hint": "Track the active logbook, integrations, and current callsign history without leaving the main screen.",
        "section.quick_filters": "Quick filters",
        "label.callsign": "Callsign",
        "label.date": "Date",
        "label.time": "Time",
        "label.frequency_mhz": "Frequency MHz",
        "label.mode": "Mode",
        "label.rst_sent": "RST Sent",
        "label.rst_recv": "RST Recv",
        "label.operator": "Operator",
        "label.station": "Station",
        "label.notes": "Notes",
        "placeholder.callsign": "PY2XXX",
        "placeholder.date": "YYYY-MM-DD",
        "placeholder.time": "HH:MM",
        "placeholder.frequency": "14.074",
        "placeholder.mode": "SSB, CW, FT8",
        "placeholder.rst": "59",
        "placeholder.operator": "Operator callsign",
        "placeholder.station": "Station callsign",
        "placeholder.notes": "Notes about the contact",
        "placeholder.search_callsign": "Search callsign",
        "button.save_qso": "Save QSO",
        "button.update_qso": "Update QSO",
        "button.new_qso": "New QSO",
        "button.search": "Search",
        "button.show_recent": "Show Recent",
        "button.edit_selected": "Edit Selected",
        "button.delete_selected": "Delete Selected",
        "button.manage_logbooks": "Manage",
        "button.new_profile": "New profile",
        "button.save_profile": "Save profile",
        "button.delete_profile": "Delete profile",
        "button.new_logbook": "New logbook",
        "button.save_logbook": "Save logbook",
        "button.delete_logbook": "Delete logbook",
        "button.close": "Close",
        "table.recent.id": "ID",
        "table.recent.callsign": "Callsign",
        "table.recent.date": "Date",
        "table.recent.time": "Time",
        "table.recent.band": "Band",
        "table.recent.mode": "Mode",
        "table.history.id": "ID",
        "table.history.date": "Date",
        "table.history.time": "Time",
        "table.history.band": "Band",
        "table.history.mode": "Mode",
        "table.history.rst": "RST",
        "status.ready_first": "Ready to register the first QSO.",
        "status.ready_next": "Ready to register the next QSO.",
        "status.search_loaded": "{count} QSO(s) loaded for search.",
        "status.editing": "Editing QSO #{qso_id} for {callsign}.",
        "status.deleted": "QSO #{qso_id} deleted.",
        "status.logbook_changed": "Active logbook changed to {name}.",
        "status.saved": "QSO #{qso_id} {action} for {callsign} on {band} {mode}.{warnings}",
        "status.adif_imported": "ADIF import finished. {imported} imported, {skipped} skipped, {failed} failed.",
        "status.adif_exported": "ADIF export finished. {exported} QSO(s) exported.",
        "status.history_prompt": "Type or select a callsign to inspect previous QSOs.",
        "status.history_found": "{count} previous QSO(s) found for {callsign}.",
        "status.history_empty": "No previous QSOs found for {callsign}.",
        "status.integration_logged": "{source} logged {callsign} on {band} {mode}.",
        "status.integration_parse_failed": "Failed to parse ADIF received from {source}.",
        "status.integration_save_failed": "Failed to save QSO received from {source}: {detail}",
        "status.clublog_queued": "Club Log upload queued. {detail}",
        "status.clublog_upload_ok": "Club Log updated successfully. {detail}",
        "status.clublog_upload_failed": "Club Log upload failed. {detail}",
        "message.invalid_data_title": "Invalid data",
        "message.invalid_frequency": "Frequency must be a valid decimal number.",
        "message.validation_error_title": "Validation error",
        "message.qso_saved_title": "QSO saved",
        "message.qso_saved_body": "QSO #{qso_id} {action} for {callsign} on {band}.",
        "message.qso_not_found_title": "QSO not found",
        "message.qso_not_found_body": "QSO #{qso_id} was not found.",
        "message.delete_title": "Delete QSO",
        "message.delete_body": "Do you want to delete QSO #{qso_id}?",
        "message.delete_failed_title": "Delete failed",
        "message.delete_failed_body": "QSO #{qso_id} could not be deleted.",
        "action.saved": "saved",
        "action.updated": "updated",
        "about.title": "About PyCQLog",
        "about.body": (
            "<h2>PyCQLog</h2>"
            "<p>Desktop amateur radio logging application built with Python and PyQt.</p>"
            "<p><b>Author:</b> Claudio - PY9MT<br>"
            "<b>Technical co-creation:</b> CODEX</p>"
            "<p>This system is being built with support from highly qualified AI, "
            "focused on strategic value, development speed, and architectural quality.</p>"
        ),
        "settings.title": "Settings",
        "settings.language": "Language",
        "settings.theme": "Theme",
        "settings.operator_callsign": "Default operator callsign",
        "settings.station_callsign": "Default station callsign",
        "settings.data_dir": "Data directory",
        "settings.data_dir_help": "Defines where PyCQLog stores the local database and settings.",
        "settings.log_dir": "Default logs directory",
        "settings.log_dir_help": "Defines the default folder for ADIF files and other logs.",
        "settings.choose_directory": "Choose folder",
        "settings.restart_notice": "Some changes may require a restart to be reflected across the full application.",
        "settings.saved_title": "Settings saved",
        "settings.saved_body": "Settings were saved successfully.",
        "settings.invalid_data_dir_title": "Invalid directory",
        "settings.invalid_data_dir_body": "The selected directory could not be created or accessed.",
        "settings.directory_dialog_title": "Select data directory",
        "settings.invalid_log_dir_title": "Invalid logs directory",
        "settings.invalid_log_dir_body": "The default logs directory could not be created or accessed.",
        "settings.log_dir_dialog_title": "Select default logs directory",
        "directories.title": "Directories",
        "directories.help": "Defines the paths used by the system for the local database and log files.",
        "logbooks.title": "Logbooks",
        "logbooks.active": "Active logbook",
        "logbooks.name": "Name",
        "logbooks.description": "Description",
        "logbooks.operator_profile": "Operator profile",
        "logbooks.station_profile": "Station profile",
        "logbooks.no_profile": "No profile",
        "logbooks.qso_count": "QSOs",
        "logbooks.help": "Each logbook can represent a distinct operation such as main, contest, portable, or expedition.",
        "logbooks.name_required": "Please provide a name for the logbook.",
        "logbooks.delete_title": "Delete logbook",
        "logbooks.delete_body": "Do you want to delete the selected logbook? Its QSOs will also be removed.",
        "logbooks.delete_blocked_title": "Delete blocked",
        "logbooks.delete_blocked_body": "It is not possible to delete the last remaining logbook.",
        "profiles.title": "Station and operator profiles",
        "profiles.name": "Profile name",
        "profiles.type": "Type",
        "profiles.type_both": "Operator and station",
        "profiles.type_operator": "Operator only",
        "profiles.type_station": "Station only",
        "profiles.qth": "QTH",
        "profiles.locator": "Locator",
        "profiles.power": "Power",
        "profiles.antenna": "Antenna",
        "profiles.help": "Reusable profiles help build logbooks and operations with consistent data.",
        "profiles.name_required": "Please provide a name for the profile.",
        "profiles.delete_title": "Delete profile",
        "profiles.delete_body": "Do you want to delete the selected profile?",
        "integrations.title": "Integrations",
        "integrations.wsjt_enabled": "Enable automatic capture via WSJT-X / JTDX UDP",
        "integrations.wsjt_debug": "Enable UDP Debug (Show all packets in Monitor)",
        "integrations.wsjt_host": "Local UDP host",
        "integrations.wsjt_port": "UDP port",
        "integrations.clublog_enabled": "Enable automatic Club Log upload",
        "integrations.clublog_upload_udp": "Automatically upload QSOs received via WSJT-X / JTDX",
        "integrations.clublog_upload_manual": "Automatically upload manually saved QSOs",
        "integrations.clublog_email": "Club Log email",
        "integrations.clublog_password": "Club Log app password",
        "integrations.clublog_callsign": "Primary callsign",
        "integrations.clublog_api_key": "API key",
        "integrations.clublog_endpoint": "Upload endpoint",
        "integrations.clublog_delete_endpoint": "Delete endpoint",
        "integrations.clublog_interval": "Minimum interval between uploads (s)",
        "integrations.qrz_enabled": "Enable automatic QRZ.com upload",
        "integrations.qrz_upload_udp": "Automatically upload QSOs received via WSJT-X",
        "integrations.qrz_upload_manual": "Automatically upload manually saved QSOs",
        "integrations.qrz_username": "QRZ Username (For XML lookups)",
        "integrations.qrz_password": "QRZ Password",
        "integrations.qrz_api_key": "QRZ Logbook API Key (For upload)",
        "integrations.lotw_tqsl_path": "tqsl executable / path",
        "integrations.lotw_station_location": "Station Location (TQSL)",
        "integrations.tab_local": "WSJT-X",
        "integrations.tab_clublog": "Club Log",
        "integrations.tab_qrz": "QRZ.com",
        "integrations.tab_lotw": "LoTW",
        "integrations.tab_service": "Service",
        "integrations.service_remote_enabled": "Use a remote daemon in this UI",
        "integrations.service_remote_host": "Daemon IP/host",
        "integrations.service_remote_port": "Daemon port",
        "integrations.service_auth_code": "Authentication code",
        "integrations.service_auth_generate": "Generate code",
        "integrations.service_help": "These options only control how the desktop UI connects to a remote daemon. Daemon-side settings stay in the pycqlog_daemon.conf file.",
        "integrations.help": "Configure integration parameters across tabs. QRZ lookups require Username/Password with XML subscription. QRZ logbook upload requires the API Key. The tqsl utility must be installed for LoTW.",
        "integrations.monitor_title": "Integration Monitor",
        "integrations.monitor_listener": "UDP listener",
        "integrations.monitor_clublog": "Club Log",
        "integrations.monitor_received": "Packets received",
        "integrations.monitor_saved": "QSOs saved",
        "integrations.monitor_uploaded": "Uploads completed",
        "integrations.monitor_failed": "Failures",
        "integrations.monitor_pending": "Pending",
        "integrations.monitor_time": "Time",
        "integrations.monitor_source": "Source",
        "integrations.monitor_event": "Event",
        "integrations.monitor_detail": "Detail",
        "integrations.monitor_on": "Enabled",
        "integrations.monitor_off": "Disabled",
        "integrations.monitor_test_udp": "Test UDP",
        "integrations.monitor_test_clublog": "Test Club Log",
        "integrations.monitor_retry_pending": "Retry pending",
        "integrations.monitor_clear": "Clear history",
        "integrations.event_received": "Packet received",
        "integrations.event_saved": "QSO saved",
        "integrations.event_uploaded": "Upload completed",
        "integrations.event_upload_failed": "Upload failed",
        "integrations.event_queued": "Upload queued",
        "integrations.event_parse_failed": "Parse failed",
        "integrations.event_save_failed": "Save failed",
        "integrations.event_test_udp": "UDP test triggered",
        "integrations.event_test_clublog": "Club Log test queued",
        "integrations.event_test_clublog_failed": "Club Log test blocked",
        "integrations.event_retry_pending": "Pending jobs requeued",
        "integrations.test_udp_detail": "A synthetic ADIF packet was injected into the local queue.",
        "button.save_settings": "Save settings",
        "button.cancel": "Cancel",
        "adif.dialog_title": "Select ADIF file",
        "adif.settings_title": "ADIF Preferences",
        "adif.settings_help": "Defines the default values used in the form and in the suggested ADIF export filename.",
        "adif.export_prefix": "Export filename prefix",
        "adif.export_prefix_placeholder": "pycqlog_export",
        "adif.import_title": "ADIF Import",
        "adif.import_result": "{imported} QSO(s) imported, {skipped} skipped, {failed} failed.",
        "adif.export_dialog_title": "Save ADIF export",
        "adif.export_filters_title": "ADIF export filters",
        "adif.export_filters_help": "All filters are optional. Dates must use the format YYYY-MM-DD.",
        "adif.export_choose_file": "Choose file",
        "adif.export_date_from": "Start date",
        "adif.export_date_to": "End date",
        "adif.export_band": "Band",
        "adif.export_title": "ADIF Export",
        "adif.export_result": "{exported} QSO(s) exported to:\n{destination}",
        "adif.preview_title": "ADIF import preview",
        "adif.preview_summary": "Total: {total} | Ready: {ready} | Skipped: {skipped} | Failed: {failed}",
        "adif.preview_import": "Import",
        "adif.preview_status": "Status",
        "adif.preview_confirm": "Import now",
        "adif.filter_label": "Filter",
        "adif.filter_all": "All",
        "adif.filter_ready": "Ready",
        "adif.filter_skipped": "Skipped",
        "adif.filter_failed": "Failed",
        "adif.select_ready": "Select ready",
        "adif.clear_selection": "Clear selection",
        "filter.band": "Bands",
        "filter.mode": "Modes",
        "filter.clear": "Clear filters",
        "theme.system": "Use system theme",
        "theme.light": "Light",
        "theme.dark": "Dark",
        "dashboard.title": "Operations Dashboard",
        "dashboard.active_logbook": "Active logbook: {name}",
        "dashboard.period": "Period",
        "dashboard.period_all": "Whole log",
        "dashboard.period_7d": "Last 7 days",
        "dashboard.period_30d": "Last 30 days",
        "dashboard.period_365d": "Last 12 months",
        "dashboard.settings_menu": "Colors and appearance",
        "dashboard.settings_title": "Dashboard Colors",
        "dashboard.settings_band_colors": "Use band colors in band charts",
        "dashboard.settings_mode_colors": "Use mode colors in mode charts",
        "dashboard.settings_table_colors": "Also colorize band and mode in main tables",
        "summary.logbook": "Logbook",
        "summary.integrations": "Integrations",
        "summary.pending": "Pending",
        "summary.status": "Operating status",
        "summary.visible_qsos": "{count} QSO(s) visible in this list.",
        "summary.logbook_detail": "{name} with {count} QSO(s) in the active log.",
        "summary.logbook_footer": "Logbook: {name} ({count} QSOs)",
        "summary.integration_listener_on": "UDP ready",
        "summary.integration_listener_off": "UDP idle",
        "summary.integration_cloud_on": "Upload ready",
        "summary.integration_cloud_off": "Upload limited",
        "summary.integrations_detail": "Listener: {listener}\nClub Log: {cloud}\nPending queue: {pending}",
        "summary.integrations_footer": "Integrations: UDP {listener} | Club Log {cloud}",
        "summary.pending_footer": "Queue: {pending}",
        "dashboard.settings_help": "When enabled, dashboard charts use specific palettes for band and operating mode. These colors can also be applied to the operating tables.",
        "dashboard.total_qsos": "Total QSOs",
        "dashboard.unique_callsigns": "Unique callsigns",
        "dashboard.active_bands": "Active bands",
        "dashboard.active_modes": "Active modes",
        "dashboard.dxcc_entities": "Estimated DXCC",
        "dashboard.waz_zones": "CQ zones",
        "dashboard.wpx_prefixes": "WPX prefixes",
        "dashboard.chart_bands": "QSOs by band",
        "dashboard.chart_modes": "QSOs by mode",
        "dashboard.chart_days": "QSOs by day",
        "dashboard.chart_months": "Monthly trend",
        "dashboard.chart_hours": "QSOs by hour",
        "dashboard.top_callsigns": "Top callsigns",
        "dashboard.contacts": "Contacts",
    },
}


@dataclass
class LocalizationService:
    language: str

    def __post_init__(self) -> None:
        if self.language not in TRANSLATIONS:
            self.language = "en"

    def set_language(self, language: str) -> None:
        if language in TRANSLATIONS:
            self.language = language

    def t(self, key: str, **kwargs: object) -> str:
        text = TRANSLATIONS.get(self.language, {}).get(key)
        if text is None:
            text = TRANSLATIONS["en"].get(key, key)
        return text.format(**kwargs) if kwargs else text

    def available_languages(self) -> list[str]:
        return list(TRANSLATIONS.keys())
