from __future__ import annotations

from pathlib import Path


OUTPUT = Path(__file__).with_name("sample_900_qsos.adi")


def adif_field(name: str, value: str) -> str:
    return f"<{name}:{len(value)}>{value}"


def build_record(**fields: str) -> str:
    parts = [adif_field(name, value) for name, value in fields.items()]
    return "".join(parts) + "<EOR>\n"


def main() -> None:
    lines = [
        "Generated by PyCQLog test data",
        "<ADIF_VER:5>3.1.0",
        "<PROGRAMID:7>PyCQLog",
        "<EOH>",
    ]

    for i in range(1, 301):
        day = (i - 1) % 28 + 1
        hour = (i - 1) % 24
        minute = (i * 3) % 60
        second = (i * 7) % 60
        freq = f"14.{70 + (i % 10):03d}"
        lines.append(
            build_record(
                CALL=f"K1{i:03d}",
                QSO_DATE=f"202603{day:02d}",
                TIME_ON=f"{hour:02d}{minute:02d}{second:02d}",
                FREQ=freq,
                MODE="MFSK",
                SUBMODE="FT8",
                RST_SENT="59",
                RST_RCVD="55",
                OPERATOR="PY9MT",
                STATION_CALLSIGN="PY9MT",
                COMMENT=f"FT8 TEST {i:03d}",
            ).rstrip("\n")
        )

    for i in range(1, 301):
        n = i + 300
        day = (i - 1) % 28 + 1
        hour = (i + 5) % 24
        minute = (i * 5) % 60
        second = (i * 11) % 60
        freq = f"7.{10 + (i % 40):03d}"
        lines.append(
            build_record(
                CALL=f"W2{i:03d}",
                QSO_DATE=f"202604{day:02d}",
                TIME_ON=f"{hour:02d}{minute:02d}{second:02d}",
                FREQ=freq,
                MODE="CW",
                RST_SENT="599",
                RST_RCVD="579",
                OPERATOR="PY9MT",
                STATION_CALLSIGN="PY9MT",
                COMMENT=f"CW TEST {n:03d}",
            ).rstrip("\n")
        )

    for i in range(1, 301):
        n = i + 600
        day = (i - 1) % 28 + 1
        hour = (i + 11) % 24
        minute = (i * 7) % 60
        second = (i * 13) % 60
        freq = f"21.{200 + (i % 100):03d}"
        lines.append(
            build_record(
                CALL=f"LU3{i:03d}",
                QSO_DATE=f"202605{day:02d}",
                TIME_ON=f"{hour:02d}{minute:02d}{second:02d}",
                FREQ=freq,
                MODE="SSB",
                RST_SENT="59",
                RST_RCVD="59",
                OPERATOR="PY9MT",
                STATION_CALLSIGN="PY9MT",
                COMMENT=f"SSB TEST {n:03d}",
            ).rstrip("\n")
        )

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
