from __future__ import annotations


AWARD_RULES: tuple[tuple[str, str, int | None], ...] = (
    ("3B8", "Mauritius", 39),
    ("3B9", "Rodriguez Island", 39),
    ("4X", "Israel", 20),
    ("5B", "Cyprus", 20),
    ("5H", "Tanzania", 37),
    ("5R", "Madagascar", 39),
    ("5Z", "Kenya", 37),
    ("7Q", "Malawi", 37),
    ("9A", "Croatia", 15),
    ("9K", "Kuwait", 21),
    ("9M2", "West Malaysia", 28),
    ("9M6", "East Malaysia", 28),
    ("9V", "Singapore", 28),
    ("9Y", "Trinidad and Tobago", 9),
    ("A4", "Oman", 21),
    ("A6", "United Arab Emirates", 21),
    ("AP", "Pakistan", 21),
    ("BV", "Taiwan", 24),
    ("BY", "China", 24),
    ("CE", "Chile", 12),
    ("CM", "Cuba", 8),
    ("CO", "Cuba", 8),
    ("CP", "Bolivia", 10),
    ("CT", "Portugal", 14),
    ("CX", "Uruguay", 13),
    ("DL", "Germany", 14),
    ("DU", "Philippines", 27),
    ("EA8", "Canary Islands", 33),
    ("EA", "Spain", 14),
    ("EI", "Ireland", 14),
    ("ER", "Moldova", 16),
    ("ES", "Estonia", 15),
    ("EU", "Belarus", 16),
    ("EX", "Kyrgyzstan", 17),
    ("EY", "Tajikistan", 17),
    ("EZ", "Turkmenistan", 17),
    ("FG", "Guadeloupe", 8),
    ("FJ", "Saint Barthelemy", 8),
    ("FK", "New Caledonia", 32),
    ("FM", "Martinique", 8),
    ("FO", "French Polynesia", 32),
    ("FR", "Reunion Island", 39),
    ("G", "England", 14),
    ("GM", "Scotland", 14),
    ("GW", "Wales", 14),
    ("GI", "Northern Ireland", 14),
    ("GU", "Guernsey", 14),
    ("HC", "Ecuador", 10),
    ("HI", "Dominican Republic", 8),
    ("HK", "Colombia", 9),
    ("HL", "South Korea", 25),
    ("HS", "Thailand", 26),
    ("HZ", "Saudi Arabia", 21),
    ("I", "Italy", 15),
    ("JA", "Japan", 25),
    ("JE", "Japan", 25),
    ("JF", "Japan", 25),
    ("JG", "Japan", 25),
    ("JH", "Japan", 25),
    ("JI", "Japan", 25),
    ("JJ", "Japan", 25),
    ("JK", "Japan", 25),
    ("JL", "Japan", 25),
    ("JM", "Japan", 25),
    ("JN", "Japan", 25),
    ("JO", "Japan", 25),
    ("JP", "Japan", 25),
    ("JQ", "Japan", 25),
    ("JR", "Japan", 25),
    ("JS", "Japan", 25),
    ("JT", "Mongolia", 23),
    ("JY", "Jordan", 20),
    ("KH0", "Northern Mariana Islands", 27),
    ("KH2", "Guam", 27),
    ("KH6", "Hawaii", 31),
    ("KL", "Alaska", 1),
    ("KP2", "US Virgin Islands", 8),
    ("KP4", "Puerto Rico", 8),
    ("LA", "Norway", 14),
    ("LU", "Argentina", 13),
    ("LW", "Argentina", 13),
    ("LY", "Lithuania", 15),
    ("LZ", "Bulgaria", 20),
    ("OA", "Peru", 10),
    ("OE", "Austria", 15),
    ("OH", "Finland", 15),
    ("OK", "Czech Republic", 15),
    ("OM", "Slovakia", 15),
    ("ON", "Belgium", 14),
    ("OZ", "Denmark", 14),
    ("PA", "Netherlands", 14),
    ("PY", "Brazil", 11),
    ("PP", "Brazil", 11),
    ("PQ", "Brazil", 11),
    ("PR", "Brazil", 11),
    ("PS", "Brazil", 11),
    ("PT", "Brazil", 11),
    ("PU", "Brazil", 11),
    ("PV", "Brazil", 11),
    ("PW", "Brazil", 11),
    ("PX", "Brazil", 11),
    ("P2", "Papua New Guinea", 28),
    ("S5", "Slovenia", 15),
    ("SM", "Sweden", 14),
    ("SP", "Poland", 15),
    ("SV", "Greece", 20),
    ("TG", "Guatemala", 7),
    ("TI", "Costa Rica", 7),
    ("UA9", "Asiatic Russia", 17),
    ("UA", "European Russia", 16),
    ("UN", "Kazakhstan", 17),
    ("UR", "Ukraine", 16),
    ("V2", "Antigua and Barbuda", 8),
    ("V5", "Namibia", 38),
    ("VE", "Canada", 4),
    ("VK", "Australia", 30),
    ("VR2", "Hong Kong", 24),
    ("VU", "India", 22),
    ("XE", "Mexico", 6),
    ("XQ", "Chile", 12),
    ("YB", "Indonesia", 28),
    ("YO", "Romania", 20),
    ("YT", "Serbia", 15),
    ("YU", "Serbia", 15),
    ("YV", "Venezuela", 9),
    ("ZL", "New Zealand", 32),
    ("ZP", "Paraguay", 11),
    ("ZS", "South Africa", 38),
    ("ZY", "Brazil", 11),
    ("ZZ", "Brazil", 11),
    ("AA", "United States", 5),
    ("AB", "United States", 5),
    ("AC", "United States", 5),
    ("AD", "United States", 5),
    ("AE", "United States", 5),
    ("AF", "United States", 5),
    ("AG", "United States", 5),
    ("AI", "United States", 5),
    ("AJ", "United States", 5),
    ("AK", "United States", 5),
    ("AL", "United States", 5),
    ("AY", "Argentina", 13),
    ("AZ", "Argentina", 13),
    ("K", "United States", 5),
    ("M", "England", 14),
    ("N", "United States", 5),
    ("W", "United States", 5),
    ("F", "France", 14),
    ("HB", "Switzerland", 14),
    ("2E", "England", 14),
)
