from __future__ import annotations

from typing import Protocol

from pycqlog.application.dto import CallbookData
from pycqlog.domain.models import Logbook, LogbookDraft, Qso, QsoDraft, StationProfile, StationProfileDraft

class CallbookPort(Protocol):
    def lookup(self, callsign: str) -> CallbookData | None: ...

class QsoRepository(Protocol):
    def save(self, draft: QsoDraft) -> Qso: ...

    def list_all(self) -> list[Qso]: ...

    def list_recent(self, limit: int = 50) -> list[Qso]: ...

    def get_by_id(self, qso_id: int) -> Qso | None: ...

    def update(self, qso_id: int, draft: QsoDraft) -> Qso | None: ...

    def delete(self, qso_id: int) -> bool: ...

    def search(self, callsign: str, limit: int = 50) -> list[Qso]: ...

    def find_duplicate(self, draft: QsoDraft) -> Qso | None: ...


class LogbookRepository(Protocol):
    def ensure_default_logbook(self) -> Logbook: ...

    def list_logbooks(self) -> list[Logbook]: ...

    def get_logbook(self, logbook_id: int) -> Logbook | None: ...

    def save_logbook(self, draft: LogbookDraft, logbook_id: int | None = None) -> Logbook: ...

    def delete_logbook(self, logbook_id: int) -> bool: ...

    def get_active_logbook(self) -> Logbook: ...

    def set_active_logbook(self, logbook_id: int) -> Logbook: ...


class StationProfileRepository(Protocol):
    def list_station_profiles(self) -> list[StationProfile]: ...

    def get_station_profile(self, profile_id: int) -> StationProfile | None: ...

    def save_station_profile(
        self,
        draft: StationProfileDraft,
        profile_id: int | None = None,
    ) -> StationProfile: ...

    def delete_station_profile(self, profile_id: int) -> bool: ...
