from __future__ import annotations

from datetime import datetime
from pathlib import Path

from pycqlog.domain.models import Qso


class AdifExporter:
    def export(self, qsos: list[Qso], destination: Path) -> int:
        destination.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "Generated by PyCQLog export",
            "<ADIF_VER:5>3.1.0",
            "<PROGRAMID:7>PyCQLog",
            f"<CREATED_TIMESTAMP:15>{datetime.utcnow().strftime('%Y%m%d %H%M%S')}",
            "<EOH>",
        ]
        for qso in qsos:
            lines.append(self.build_record(qso))
        destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return len(qsos)

    def build_record(self, qso: Qso) -> str:
        fields: list[tuple[str, str]] = [
            ("CALL", qso.callsign),
            ("QSO_DATE", qso.qso_date.strftime("%Y%m%d")),
            ("TIME_ON", qso.time_on.strftime("%H%M%S")),
            ("FREQ", str(qso.freq)),
            ("BAND", qso.band),
            ("MODE", qso.mode),
        ]
        if qso.rst_sent:
            fields.append(("RST_SENT", qso.rst_sent))
        if qso.rst_recv:
            fields.append(("RST_RCVD", qso.rst_recv))
        if qso.operator:
            fields.append(("OPERATOR", qso.operator))
        if qso.station_callsign:
            fields.append(("STATION_CALLSIGN", qso.station_callsign))
        if qso.notes:
            fields.append(("COMMENT", qso.notes))
        if qso.source:
            fields.append(("APP_PYCQLOG_SOURCE", qso.source))
        return "".join(self._field(name, value) for name, value in fields) + "<EOR>"

    def _field(self, name: str, value: str) -> str:
        return f"<{name}:{len(value)}>{value}"
